###############################################################################
# Vbar
###############################################################################
#' Generate The Main Graphical Objects
#'
#' @name main_grobs
#'
#' @description
#' These functions create the graphical objects for the main diagram area of the
#' different diagram types. These functions don't work on their own. They have to
#' be used inside a custom diagram function, which builds the whole diagram and can
#' be plugged into the "diagram" parameter of [design_graphic()].
#'
#' [vertical_grouped_bar_grob()]: Set up the main segments for vertical bars.
#'
#' @param diagram_info The list of measurements generated by [get_diagram_dimensions()].
#' @param arguments Argument list passed passed on by [design_graphic()].
#'
#' @return
#' Returns a grid::gList containing segments and labels.
#'
#' @rdname main_grobs
#'
#' @export
vertical_grouped_bar_grob <- function(diagram_info, arguments){
    visuals           <- arguments[["visuals"]]
    dimensions        <- arguments[["dimensions"]]
    fine_tuning       <- arguments[["fine_tuning"]]
    value_y_pos       <- diagram_info[["values"]]
    theme             <- diagram_info[["theme"]]
    color_usage       <- diagram_info[["color_usage"]]
    theme_override    <- diagram_info[["theme_override"]]
    font_color        <- diagram_info[["font_color"]]
    colors_outside    <- diagram_info[["colors_outside"]]
    values_fit_inside <- diagram_info[["values_fit_vertical"]]

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate rectangles
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Inject overrides
    if (length(theme_override) > 0){
        for (override in theme_override){
            diagram_info[["colors_to_use"]][override[["number"]]] <- override[["color"]]
            diagram_info[["border_color"]][override[["number"]]]  <- override[["border_color"]]
        }
    }

    # Every segment is drawn as a separate element so that it can be accessed
    # individually even after graphic completion.
    # NOTE: For the width a tiny bit is subtracted because the bars would otherwise
    #       overlap by one pixel, in case colored outlines are used.
    rects <- do.call(grid::gList,
                     lapply(seq_len(diagram_info[["number_of_elements"]]), function(i){
        grid::rectGrob(x      = grid::unit(diagram_info[["segment_pos"]][i], "native") + (diagram_info[["shrink_width"]] / 2),
                       y      = grid::unit(diagram_info[["zero_pos"]], "native"),
                       width  = grid::unit(diagram_info[["segment_width"]], "native") - diagram_info[["shrink_width"]],
                       height = grid::unit(diagram_info[["actual_drawing_height"]][i], "native"),
                       just   = c("left", "bottom"),
                       name   = paste0("tooltip_segment_g", diagram_info[["group_ids"]][i] + 1, "_s", diagram_info[["segment_ids"]][i] + 1),
                       gp     = grid::gpar(fill = diagram_info[["colors_to_use"]][i],
                                           col  = diagram_info[["border_color"]][i],
                                           lwd  = dimensions[["line_thickness"]]))
    }))

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate value texts
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    if (visuals[["display_values"]]){
        number_of_values <- length(value_y_pos)

        hjust  <- numeric(number_of_values)
        vjust  <- numeric(number_of_values)
        rotate <- numeric(number_of_values)

        # If a small scale is used it can happen that a negative symbol appears in front
        # of 0 values. This gets removed here.
        formatted_values                   <- diagram_info[["formatted_values"]]
        formatted_values[value_y_pos == 0] <- sub("\u2013", "", formatted_values[value_y_pos == 0])

        y_offset <- rep(grid::unit(0, "mm"), number_of_values)

        if (!visuals[["rotate_values"]]){
            hjust  <- rep(fine_tuning[["values_hjust"]], number_of_values)
            rotate <- rep(0, number_of_values)

            if (visuals[["bar_values_inside"]]){
                # Set up values drawn inside and outside the segments
                vjust[values_fit_inside]  <- diagram_info[["values_inner_vjust"]][values_fit_inside]
                vjust[!values_fit_inside] <- diagram_info[["values_outer_vjust"]][!values_fit_inside]
            }
            # Set up values drawn outside segments
            else{
                vjust      <- diagram_info[["values_outer_vjust"]]
                font_color <- colors_outside
            }
        }
        # Set up with rotated values
        else{
            vjust_base <- fine_tuning[["values_hjust_90"]]
            rotate     <- rep(visuals[["value_rotation"]], number_of_values)

            if (visuals[["bar_values_inside"]]){
                # Set up values drawn inside segments
                hjust[values_fit_inside] <- diagram_info[["values_inner_vjust"]][values_fit_inside]
                vjust[values_fit_inside] <- vjust_base + fine_tuning[["values_hjust_90_plus"]]

                # Set up justification for values that don't fit inside the bars
                hjust[!values_fit_inside] <- diagram_info[["values_outer_vjust"]][!values_fit_inside]
                vjust[!values_fit_inside] <- vjust_base

                # Justification is set to the extremes depending on whether values
                # are positive or negative. Instead of setting the value offset via
                # justification, a fixed offset is added to the y coordinate.
                y_offset <- data.table::fifelse(hjust <= 0,
                                                grid::unit(fine_tuning[["values_vjust_90_positive"]], "mm"),
                                                grid::unit(-fine_tuning[["values_vjust_90_positive"]] + fine_tuning[["values_vjust_90_negative"]], "mm"))
                hjust    <- data.table::fifelse(hjust <= 0, 0, 1)
            }
            # All values drawn outside the bars
            else{
                # Justification is set to the extremes depending on whether values
                # are positive or negative. Instead of setting the value offset via
                # justification, a fixed offset is added to the y coordinate.
                hjust      <- data.table::fifelse(value_y_pos >= 0, 0, 1)
                y_offset   <- data.table::fifelse(value_y_pos >= 0,
                                                  grid::unit(fine_tuning[["values_vjust_90_positive"]], "mm"),
                                                  grid::unit(-fine_tuning[["values_vjust_90_positive"]], "mm"))

                vjust      <- vjust_base
                font_color <- colors_outside
            }
        }

        # If all values are negative and the y axes is at the top of the diagram,
        # 0 values should be drawn below the y axes.
        if (collapse::fmax(value_y_pos) == 0){
            if (!visuals[["rotate_values"]]){
                vjust[value_y_pos == 0] <- fine_tuning[["values_below_axes_just"]]
            }
            else{
                hjust[value_y_pos == 0] <- fine_tuning[["values_below_axes_90_just"]]
            }
        }

        # Add offset to y axes for values equal to 0 if they are rotated
        if (visuals[["rotate_values"]]){
            value_y_pos[value_y_pos == 0] <- grid::convertUnit(grid::unit(fine_tuning[["values_zero_line_offset"]], "cm"),
                                                               "native", valueOnly = TRUE) * diagram_info[["primary_y_distance"]]
        }

        # Inject overrides
        if (length(theme_override) > 0){
            for (override in theme_override){
                font_color[override[["number"]]] <- override[["font_color"]]
            }
        }

        # Generate formatted values. Every value is drawn as a separate element
        # so that it can be accessed individually even after graphic completion.
        texts <- do.call(grid::gList,
                         lapply(seq_len(number_of_values), function(i){
            grid::textGrob(formatted_values[i],
                           x      = grid::unit(diagram_info[["values_x_pos"]][i], "native"),
                           y      = grid::unit(value_y_pos[i], "native") + y_offset[i],
                           vjust  = vjust[i],
                           hjust  = hjust[i],
                           rot    = rotate[i],
                           name   = paste0("segment_value", i),
                           gp     = grid::gpar(col        = font_color[i],
                                               fontfamily = visuals[["font"]],
                                               fontsize   = dimensions[["value_font_size"]],
                                               fontface   = visuals[["value_font_face"]],
                                               lineheight = dimensions[["line_height"]]))
        }))
    }
    else{
        texts <- grid::nullGrob(name = "no_vbars")
    }

    # Return final segments
    if (inherits(texts, "gList")){
        list(grid::gList(rects, texts), grid::convertUnit(grid::unit(value_y_pos, "native") + y_offset, "native", valueOnly = TRUE))
    }
    else{
        list(grid::gList(rects), value_y_pos)
    }
}


#' @description
#' [vertical_stacked_bar_grob()]: Set up the main segments for vertical bars.
#'
#' @param diagram_info The list of measurements generated by [get_diagram_dimensions()].
#' @param arguments Argument list passed passed on by [design_graphic()].
#'
#' @rdname main_grobs
#'
#' @export
vertical_stacked_bar_grob <- function(diagram_info, arguments){
    visuals           <- arguments[["visuals"]]
    dimensions        <- arguments[["dimensions"]]
    fine_tuning       <- arguments[["fine_tuning"]]
    value_y_pos       <- diagram_info[["values"]]
    theme             <- diagram_info[["theme"]]
    color_usage       <- diagram_info[["color_usage"]]
    theme_override    <- diagram_info[["theme_override"]]
    font_color        <- diagram_info[["font_color"]]
    colors_outside    <- diagram_info[["colors_outside"]]
    values_fit_inside <- diagram_info[["values_fit_vertical"]]

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate rectangles
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Inject overrides
    if (length(theme_override) > 0){
        for (override in theme_override){
            diagram_info[["colors_to_use"]][override[["number"]]] <- override[["color"]]
            diagram_info[["border_color"]][override[["number"]]]  <- override[["border_color"]]
        }
    }

    stacked_values  <- unlist(diagram_info[["stacked_values"]])
    stacked_heights <- unlist(diagram_info[["stacked_heights"]])

    if (dimensions[["space_between_bars"]] == 0){
        space_between_bars <- fine_tuning[["default_stack_width"]]
    }
    else{
        space_between_bars <- dimensions[["space_between_bars"]]
    }

    stack_width <- diagram_info[["segment_width"]] * ((100 - space_between_bars) / 100)

    # Every segment is drawn as a separate element so that it can be accessed
    # individually even after graphic completion.
    # NOTE: For the width a tiny bit is subtracted because the bars would otherwise
    #       overlap by one pixel, in case colored outlines are used.
    rects <- do.call(grid::gList,
                     lapply(seq_len(diagram_info[["number_of_elements"]]), function(i){
                         seg_in_group <- ((i - 1) %% diagram_info[["number_of_segments"]]) + 1
                         group_index  <- ceiling(i / diagram_info[["number_of_segments"]])

                         grid::rectGrob(x      = grid::unit(diagram_info[["group_centers"]][i], "native"),
                                        y      = grid::unit(stacked_values[i], "native"),
                                        width  = grid::unit(stack_width, "native"),
                                        height = grid::unit(stacked_heights[i], "native"),
                                        just   = c("center", "top"),
                                        name   = paste0("tooltip_segment_g", group_index, "_s", seg_in_group),
                                        gp     = grid::gpar(fill = diagram_info[["colors_to_use"]][i],
                                                            col  = diagram_info[["border_color"]][i],
                                                            lwd  = dimensions[["line_thickness"]]))
                     }))

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate value texts
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    if (visuals[["display_values"]]){
        number_of_values <- length(value_y_pos)

        hjust  <- numeric(number_of_values)
        vjust  <- numeric(number_of_values)
        rotate <- numeric(number_of_values)

        # If a small scale is used it can happen that a negative symbol appears in front
        # of 0 values. This gets removed here.
        formatted_values                   <- diagram_info[["formatted_values"]]
        formatted_values[value_y_pos == 0] <- sub("\u2013", "", formatted_values[value_y_pos == 0])

        y_offset <- rep(grid::unit(0, "mm"), number_of_values)

        if (!visuals[["rotate_values"]]){
            vjust  <- fine_tuning[["stacked_value_vjust"]]
            rotate <- rep(0, number_of_values)

        }
        # Set up with rotated values
        else{
            vjust  <- fine_tuning[["values_hjust_90"]]
            rotate <- rep(visuals[["value_rotation"]], number_of_values)
        }

        # Inject overrides
        if (length(theme_override) > 0){
            for (override in theme_override){
                font_color[override[["number"]]] <- override[["font_color"]]
            }
        }

        stacked_centers <- unlist(diagram_info[["stacked_centers"]])

        # Generate formatted values. Every value is drawn as a separate element
        # so that it can be accessed individually even after graphic completion.
        texts <- do.call(grid::gList,
                         lapply(seq_len(number_of_values), function(i){
                             grid::textGrob(formatted_values[i],
                                            x      = grid::unit(diagram_info[["group_centers"]][i], "native"),
                                            y      = grid::unit(stacked_centers[i], "native"),
                                            vjust  = vjust,
                                            rot    = rotate[i],
                                            name   = paste0("segment_value", i),
                                            gp     = grid::gpar(col        = font_color[i],
                                                                fontfamily = visuals[["font"]],
                                                                fontsize   = dimensions[["value_font_size"]],
                                                                fontface   = visuals[["value_font_face"]],
                                                                lineheight = dimensions[["line_height"]]))
                          }))
    }
    else{
        texts <- grid::nullGrob(name = "no_vbars")
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate total value texts above stacks
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    total_texts <- grid::nullGrob(name = "no_totals")

    total_values     <- diagram_info[["total_values"]]
    number_of_stacks <- diagram_info[["number_of_stacks"]]

    if (length(total_values) > 0){
        if (length(total_values) > number_of_stacks){
            print_message("WARNING", c("There are more total values than there are stacks. This can be caused",
                                       "by the use of multiple keywords defined in the <stack_total_keywords>",
                                       " parameter withtin the <graphic_visuals>. Total values will not be drawn."))
        }
        else{
            # Get the top of each stack, which is the last element per group in
            # stacked_values.
            stacked_values <- diagram_info[["stacked_values"]]
            stack_tops <- vapply(stacked_values, function(stack_values){
                stack_values[length(stack_values)]
            }, numeric(1))

            # Measure half the total values text heights to be able to set them
            # above the stacks.
            if (!visuals[["rotate_values"]]){
                totals_height <- get_text_height(diagram_info[["formatted_totals"]],
                                                 "value",
                                                 dimensions,
                                                 visuals) / 2
            }
            else{
                totals_height <- swap_scaling(get_text_width(diagram_info[["formatted_totals"]],
                                              "value", dimensions, visuals) / 2,
                                              dimensions[["inner_canvas_width"]],
                                              dimensions[["inner_canvas_height"]]) * diagram_info[["primary_y_distance"]]
            }

            # Add fixed distance between each total value and the top of its stack
            label_offset <- grid::convertHeight(grid::unit(fine_tuning[["stacked_totals_distance"]], "mm"), "native", valueOnly = TRUE)

            if (diagram_info[["zero_pos"]] != 1){
                label_y_positions <- stack_tops + totals_height + label_offset
            }
            else{
                label_y_positions <- stack_tops - totals_height - label_offset
            }

            # Rotation only ever depended on visuals[["rotate_values"]], never on
            # zero_pos - with hjust/vjust gone there's no more branching needed here.
            rotate <- rep(if (visuals[["rotate_values"]]) visuals[["value_rotation"]] else 0, length(total_values))

            # Generate totals on top of stacks
            total_texts <- do.call(grid::gList,
                                   lapply(seq_along(total_values), function(i){
                                       grid::textGrob(diagram_info[["formatted_totals"]][i],
                                                      x      = grid::unit(diagram_info[["stack_centers"]][i], "native"),
                                                      y      = grid::unit(label_y_positions[i], "native"),
                                                      vjust  = 0.5,
                                                      hjust  = 0.5,
                                                      rot    = rotate[1],
                                                      name   = paste0("total_value", i),
                                                      gp     = grid::gpar(col        = visuals[["stack_total_font_color"]],
                                                                          fontfamily = visuals[["font"]],
                                                                          fontsize   = dimensions[["value_font_size"]],
                                                                          fontface   = visuals[["value_font_face"]],
                                                                          lineheight = dimensions[["line_height"]]))
                                   }))
        }
    }

    # Return final segments
    all_texts <- grid::gList(texts, total_texts)

    if (inherits(total_texts, "gList")){
        list(grid::gList(rects, all_texts), grid::convertUnit(grid::unit(value_y_pos, "native") + y_offset, "native", valueOnly = TRUE))
    }
    else if (inherits(texts, "gList")){
        list(grid::gList(rects, texts), grid::convertUnit(grid::unit(value_y_pos, "native") + y_offset, "native", valueOnly = TRUE))
    }
    else{
        list(grid::gList(rects), value_y_pos)
    }
}
