###############################################################################
# Vbar
###############################################################################
#' Generate The Main Graphical Objects
#'
#' @name main_grobs
#'
#' @description
#' These functions create the graphical objects for the main diagram area of the
#' different diagram types. These functions don't work on their own. They have to
#' be used inside a custom diagram function, which builds the whole diagram and can
#' be plugged into the "diagram" parameter of [design_graphic()].
#'
#' [vbar_grob()]: Set up the main segments for vertical bars.
#'
#' @param diagram_info The list of measurements generated by [get_diagram_dimensions()].
#' @param arguments Argument list passed passed on by [design_graphic()].
#'
#' @return
#' Returns a grid::gList containing segments and labels.
#'
#' @rdname main_grobs
#'
#' @export
vbar_grob <- function(diagram_info,
                      arguments){
    visuals           <- arguments[["visuals"]]
    dimensions        <- arguments[["dimensions"]]
    fine_tuning       <- arguments[["fine_tuning"]]
    value_y_pos       <- diagram_info[["values"]]
    theme             <- diagram_info[["theme"]]
    color_usage       <- diagram_info[["color_usage"]]
    theme_override    <- diagram_info[["theme_override"]]
    font_color        <- diagram_info[["font_color"]]
    colors_outside    <- diagram_info[["colors_outside"]]
    values_fit_inside <- diagram_info[["values_fit_vertical"]]

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate rectangles
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Inject overrides
    if (length(theme_override) > 0){
        for (override in theme_override){
            diagram_info[["colors_to_use"]][override[["number"]]] <- override[["color"]]
            diagram_info[["border_color"]][override[["number"]]]  <- override[["border_color"]]
        }
    }

    # Every segment is drawn as a separate element so that it can be accessed
    # individually even after graphic completion.
    # NOTE: For the width a tiny bit is subtracted because the bars would otherwise
    #       overlap by one pixel, in case colored outlines are used.
    rects <- do.call(grid::gList,
                     lapply(seq_len(diagram_info[["number_of_elements"]]), function(i){
        grid::rectGrob(x      = grid::unit(diagram_info[["segment_pos"]][i], "native") + (diagram_info[["shrink_width"]] / 2),
                       y      = diagram_info[["zero_pos"]],
                       width  = grid::unit(diagram_info[["segment_width"]], "native") - diagram_info[["shrink_width"]],
                       height = grid::unit(diagram_info[["actual_drawing_height"]][i], "native"),
                       just   = c("left", "bottom"),
                       name   = paste0("tooltip_segment", i),
                       gp     = grid::gpar(fill = diagram_info[["colors_to_use"]][i],
                                           col  = diagram_info[["border_color"]][i],
                                           lwd  = dimensions[["line_thickness"]]))
    }))

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Generate value texts
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    if (visuals[["display_values"]]){
        number_of_values <- length(value_y_pos)

        hjust      <- numeric(number_of_values)
        vjust      <- numeric(number_of_values)
        rotate     <- numeric(number_of_values)

        # If a small scale is used it can happen that a negative symbol appears in front
        # of 0 values. This gets removed here.
        formatted_values                   <- diagram_info[["formatted_values"]]
        formatted_values[value_y_pos == 0] <- sub("\u2013", "", formatted_values[value_y_pos == 0])

        y_offset <- rep(grid::unit(0, "mm"), number_of_values)

        if (!visuals[["rotate_values"]]){
            hjust  <- rep(fine_tuning[["values_hjust"]], number_of_values)
            rotate <- rep(0, number_of_values)

            if (visuals[["bar_values_inside"]]){
                # Set up values drawn inside and outside the segments
                vjust[values_fit_inside]  <- diagram_info[["values_inner_vjust"]][values_fit_inside]
                vjust[!values_fit_inside] <- diagram_info[["values_outer_vjust"]][!values_fit_inside]
            }
            # Set up values drawn outside segments
            else{
                vjust      <- diagram_info[["values_outer_vjust"]]
                font_color <- colors_outside
            }
        }
        # Set up with rotated values
        else{
            vjust_base <- fine_tuning[["values_hjust_90"]]
            rotate     <- rep(visuals[["value_rotation"]], number_of_values)

            if (visuals[["bar_values_inside"]]){
                # Set up values drawn inside segments
                hjust[values_fit_inside] <- diagram_info[["values_inner_vjust"]][values_fit_inside]
                vjust[values_fit_inside] <- vjust_base + fine_tuning[["values_hjust_90_plus"]]

                # Set up justification for values that don't fit inside the bars
                hjust[!values_fit_inside] <- diagram_info[["values_outer_vjust"]][!values_fit_inside]
                vjust[!values_fit_inside] <- vjust_base

                # Justification is set to the extremes depending on whether values
                # are positive or negative. Instead of setting the value offset via
                # justification, a fixed offset is added to the y coordinate.
                y_offset <- data.table::fifelse(hjust <= 0,
                                                grid::unit(fine_tuning[["values_vjust_90_positive"]], "mm"),
                                                grid::unit(-fine_tuning[["values_vjust_90_positive"]] + fine_tuning[["values_vjust_90_negative"]], "mm"))
                hjust    <- data.table::fifelse(hjust <= 0, 0, 1)
            }
            # All values drawn outside the bars
            else{
                # Justification is set to the extremes depending on whether values
                # are positive or negative. Instead of setting the value offset via
                # justification, a fixed offset is added to the y coordinate.
                hjust      <- data.table::fifelse(value_y_pos >= 0, 0, 1)
                y_offset   <- data.table::fifelse(value_y_pos >= 0,
                                                  grid::unit(fine_tuning[["values_vjust_90_positive"]], "mm"),
                                                  grid::unit(-fine_tuning[["values_vjust_90_positive"]], "mm"))

                vjust      <- vjust_base
                font_color <- colors_outside
            }
        }

        # If all values are negative and the y axes is at the top of the diagram,
        # 0 values should be drawn below the y axes.
        if (collapse::fmax(value_y_pos) == 0){
            if (!visuals[["rotate_values"]]){
                vjust[value_y_pos == 0] <- fine_tuning[["values_below_axes_just"]]
            }
            else{
                hjust[value_y_pos == 0] <- fine_tuning[["values_below_axes_90_just"]]
            }
        }

        # Add offset to y axes for values equal to 0 if they are rotated
        if (visuals[["rotate_values"]]){
            value_y_pos[value_y_pos == 0] <- grid::convertUnit(grid::unit(fine_tuning[["values_zero_line_offset"]], "cm"),
                                                               "native", valueOnly = TRUE) * diagram_info[["primary_y_distance"]]
        }

        # Inject overrides
        if (length(theme_override) > 0){
            for (override in theme_override){
                font_color[override[["number"]]] <- override[["font_color"]]
                font_color[override[["number"]]] <- override[["font_color"]]
            }
        }

        # Generate formatted values. Every value is drawn as a separate element
        # so that it can be accessed individually even after graphic completion.
        texts <- do.call(grid::gList,
                         lapply(seq_len(number_of_values), function(i){
            grid::textGrob(formatted_values[i],
                           x      = grid::unit(diagram_info[["values_x_pos"]][i], "native"),
                           y      = grid::unit(value_y_pos[i], "native") + y_offset[i],
                           vjust  = vjust[i],
                           hjust  = hjust[i],
                           rot    = rotate[i],
                           name   = paste0("segment_value", i),
                           gp     = grid::gpar(col        = font_color[i],
                                               fontfamily = visuals[["font"]],
                                               fontsize   = dimensions[["value_font_size"]],
                                               fontface   = visuals[["value_font_face"]],
                                               lineheight = dimensions[["line_height"]]))
        }))
    }
    else{
        texts <- grid::nullGrob(name = "no_vbars")
    }

    # Return final segments
    if (inherits(texts, "gList")){
        list(grid::gList(rects, texts), grid::convertUnit(grid::unit(value_y_pos, "native") + y_offset, "native", valueOnly = TRUE))
    }
    else{
        list(grid::gList(rects), value_y_pos)
    }
}
