#' Generate Graphics While Fully Concentrating On Design
#'
#' @description
#' [design_graphic()] produces fully styled diagrams. The many parameters are all
#' focused around making visual changes simple and fast. All diagrams can be exported
#' into multiple formats.When the [gridSVG](https://CRAN.R-project.org/package=gridSVG)
#' package is installed, it is also possible to export interactive diagrams.
#'
#' The diagram parameter takes in a function for the main diagram area, making the
#' function modular and extendable.
#'
#' @param data_frame A data frame in which are the variables to tabulate.
#' @param axes_variables A single variable combination or a vector with single variable
#' that should appear on the variable axes. To nest variables use the form:
#' "var1 + var2 + var3 + ...".
#' @param segments A vector that provides variables that should appear as the graphics
#' segments.
#' @param values A vector containing all variables that should be summarised.
#' @param statistics Available functions:
#' - "sum"       -> Weighted and unweighted sum
#' - "sum_wgt"   -> Sum of all weights
#' - "freq"      -> Unweighted frequency
#' - "freq_g0"   -> Unweighted frequency of all values greater than zero
#' - "pct_group" -> Weighted and unweighted percentages within the respective group
#' - "pct_value" -> Weighted and unweighted percentages between value variables
#' - "pct_total" -> Weighted and unweighted percentages compared to the grand total
#' - "mean"      -> Weighted and unweighted mean
#' - "median"    -> Weighted and unweighted median
#' - "mode"      -> Weighted and unweighted mode
#' - "min"       -> Minimum
#' - "max"       -> Maximum
#' - "sd"        -> Weighted and unweighted standard deviation
#' - "variance"  -> Weighted and unweighted standard variance
#' - "first"     -> First value
#' - "last"      -> Last value
#' - "pn"        -> Weighted and unweighted percentiles (any p1, p2, p3, ... possible)
#' Uses the SAS default way of calculating percentiles, which is Type 2 described in [quantile()].
#' - "missing"   -> Missings generated by the value variables
#' @param pct_group If pct_group is specified in the statistics, this option is used to
#' determine which variable of the row and column variables should add up to 100 %.
#' Multiple variables can be specified in a vector to generate multiple group percentages.
#' @param pct_value If pct_value is specified in the statistics, you can pass a list here
#' which contains the information for a new variable name and between which of the value
#' variables percentages should be computed.
#' @param formats A list in which is specified which formats should be applied to which variables.
#' @param by Compute tables stratified by the expressions of the provided variables.
#' @param weight Put in a weight variable to compute weighted results.
#' @param titles Specify one or more table titles.
#' @param footnotes Specify one or more table footnotes.
#' @param var_labels A list in which is specified which label should be printed for
#' which variable instead of the variable name.
#' @param stat_labels A list in which is specified which label should be printed for
#' which statistic instead of the statistic name.
#' @param diagram Function that provides the generation of the main diagram area. Built in are:
#' dg_vbars.
#' @param visuals Visual parameters set with [graphic_visuals()].
#' @param axes Axes parameters set with [graphic_axes()].
#' @param dimensions Dimension parameters set with [graphic_dimensions()].
#' @param fine_tuning Fine tuning parameters set with [graphic_fine_tuning()].
#' @param add_texts Use the [add_textbox()] function to freely place one or multiple textboxes.
#' @param output Output parameters set with [graphic_output()].
#' @param na.rm FALSE by default. If TRUE removes all NA values from the variables.
#' @param print TRUE by default. If TRUE prints the output, if FALSE doesn't print anything.
#' Can be used if one only wants to catch the output data frame and workbook with meta information.
#' @param monitor FALSE by default. If TRUE, outputs two charts to visualize the functions
#' time consumption.
#'
#' @details
#' [design_graphic()] is actually not based on any 'SAS' function. It is envisioned
#' to generate multiple different graphic iterations in no time. From a user perspective
#' one shouldn't have to think about "Where is the button to set the option x to y?", "In
#' which place do I have to put which piece of code to eventually make x happen?" or "In
#' which order to I have to draw which things so that hopefully the right graphic
#' prints on screen?". As a user you should only worry about "Do I use vertical or
#' horizontal bars?", "Do the colors have enough contrast?", "Do I use a legend or
#' direct segment labels?", "Should values be displayed or not?", "Should the graphic
#' be static or interactive?".
#'
#' The user shouldn't be a graphics engineer, but rather a graphics designer. So the
#' function [design_graphic()] takes care of all the tedious work and only leaves you
#' with the fun part.
#'
#' @return
#' Returns a list with the data table containing the results for the graphic and the
#' final grid::gTree graphics object.
#'
#' @seealso
#' Graphic options: [graphic_visuals()], [modify_graphic_visuals()], [graphic_axes()],
#' [modify_graphic_axes()], [graphic_dimensions()], [modify_graphic_dimensions()],
#' [graphic_output()], [modify_graphic_output()], [graphic_fine_tuning()], [modify_graphic_fine_tuning()]
#'
#' Global graphic options: [set_graphic_options()], [get_graphic_options()], [reset_graphic_options()]
#'
#' Color themes: [display_colors()], [display_themes()], [add_color_theme()], [get_theme_colors()],
#' [reset_color_themes()], [override_theme()]
#'
#' Textboxes: [add_textbox()], [get_text_width()], [get_text_height()]
#'
#' Viewport: [setup_nested_diagram_viewport()], [back_to_the_root()]
#'
#' Diagram: [get_diagram_dimensions()], [setup_interactive_elements()]
#'
#' Axes: [setup_y_axes()], [setup_x_axes()], [setup_xy_axes()]
#'
#' Labels: [direct_vertical_labels()], [setup_legend()]
#'
#' Creating formats: [discrete_format()] and [interval_format()].
#'
#' Functions that can handle formats and styles: [frequencies()], [crosstabs()], [any_table()].
#'
#' Additional functions that can handle styles: [export_with_style()]
#'
#' Additional functions that can handle formats: [summarise_plus()], [recode()],
#' [recode_multi()], [transpose_plus()], [sort_plus()]
#'
#' @examples
#' # Example data frame
#' my_data <- dummy_data(100, insert_na = FALSE)
#'
#' # Formats
#' age. <- discrete_format(
#'     "Total"          = 0:100,
#'     "under 18"       = 0:17,
#'     "18 to under 65" = 18:64,
#'     "65 and older"   = 65:100)
#'
#' sex. <- discrete_format(
#'     "Male"   = 1,
#'     "Female" = 2)
#'
#' # Design grouped vertical bar chart
#' set_titles("The qol-package brings powerful concepts from 'SAS' to 'R'.")
#' set_footnotes("To make life easier and produce bigger",
#'               "and more complex outputs in less time",
#'               "with less code.")
#'
#' my_data |>
#'      design_graphic(axes_variables = "age",
#'                     segments       = "sex",
#'                     values         = weight,
#'                     diagram        = dg_vbars,
#'                     formats        = list(sex = sex.,
#'                                           age = age.))
#'
#' # Use multiple axes grouping by just adding variables with a +
#' my_data |>
#'      design_graphic(axes_variables = "age + education",
#'                     segments       = "sex",
#'                     values         = weight,
#'                     diagram        = dg_vbars,
#'                     formats        = list(sex = sex.,
#'                                           age = age.))
#'
#' # Use multiple different segment variables within the same grouping
#' my_data |>
#'      design_graphic(axes_variables = "age",
#'                     segments       = "sex + education",
#'                     values         = weight,
#'                     diagram        = dg_vbars,
#'                     formats        = list(sex = sex.,
#'                                           age = age.))
#'
#' # Use different stylings. With the set_graphic_options() function the styling
#' # can be set globally.
#' set_graphic_options(primary_axes_max    = 100,
#'                     primary_axes_suffix = " %",
#'                     color_theme         = "violet_fire",
#'                     title_font_color    = "#FF00FF")
#'
#' my_data |>
#'      design_graphic(axes_variables = "age + education",
#'                     segments       = "sex",
#'                     values         = weight,
#'                     diagram        = dg_vbars,
#'                     formats        = list(sex = sex.,
#'                                           age = age.))
#'
#' # Another possibility is to directly plug the styling into the corresponding
#' # function parameters.
#' my_data |>
#'      design_graphic(axes_variables = "age + education",
#'                     segments       = "sex",
#'                     values         = weight,
#'                     diagram        = dg_vbars,
#'                     formats        = list(sex = sex.,
#'                                           age = age.),
#'                     dimensions = graphic_dimensions(graphic_width  = 18,
#'                                                     graphic_height = 12,
#'                                                     margins        = 0.4))
#'
#' @export
design_graphic <- function(data_frame,
                           axes_variables = "",
                           segments,
                           values,
                           statistics     = "pct_group",
                           pct_value      = list(),
                           formats        = list(),
                           by             = c(),
                           weight         = NULL,
                           titles         = .qol_options[["titles"]],
                           footnotes      = .qol_options[["footnotes"]],
                           var_labels     = .qol_options[["var_labels"]],
                           stat_labels    = .qol_options[["stat_labels"]],
                           diagram        = dg_vbars,
                           visuals        = .qol_options[["graphic_visuals"]],
                           axes           = .qol_options[["graphic_axes"]],
                           dimensions     = .qol_options[["graphic_dimensions"]],
                           fine_tuning    = .qol_options[["graphic_fine_tuning"]],
                           add_texts      = .qol_options[["graphic_texts"]],
                           output         = .qol_options[["graphic_output"]],
                           na.rm          = .qol_options[["na.rm"]],
                           print          = .qol_options[["print"]],
                           monitor        = .qol_options[["monitor"]]){

    # Measure the time
    print_start_message()
    print_step("GREY", "Error handling")

    #-------------------------------------------------------------------------#
    monitor_df <- NULL |> monitor_start("Error handling", "Preparation")
    #-------------------------------------------------------------------------#

    ###########################################################################
    # Early evaluations
    ###########################################################################

    # First convert data frame to data table
    if (!data.table::is.data.table(data_frame)){
        data_frame <- data.table::as.data.table(data_frame)
    }

    # Evaluate formats early
    if (!is_list_of_dfs(formats)){
        formats_list <- as.list(substitute(formats))[-1]
        formats      <- evaluate_formats(formats_list)
    }

    # Remove empty formats and throw a warning. This can happen if there is e.g.
    # a typo in the format.
    for (variable in names(formats)){
        if (is.null(formats[[variable]])){
            formats[[variable]] <- NULL
            print_message("WARNING", "Format for variable '[variable]' does not exist and can't be applied.", variable = variable)
        }
    }

    # Apply macros to save path and file
    if (!is.null(output[["save_path"]])){
        output[["save_path"]] <- macro(output[["save_path"]])
    }

    if (!is.null(output[["file"]])){
        output[["file"]] <- macro(output[["file"]])
    }

    ###########################################################################
    # Error handling
    ###########################################################################

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Axes variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    axes_variables <- get_origin_as_char(axes_variables, substitute(axes_variables))

    # Enable the use of macro variables
    axes_variables <- apply_macro(axes_variables)

    # Get row variables from provided combinations
    axes_vars <- unlist_variables(axes_variables)

    # If a variable vector was passed as axes variables, then treat them as single
    # variables and merge them later into one variable.
    flag_merge_axes_vars <- FALSE

    if (length(axes_variables) > 1 || !grepl("\\+", axes_variables)){
        print_message("WARNING", c("Multiple nested structures or mixed types of nested and unnested <axes variables> aren't allowed.",
                                   "All passed variables will be treated as unnested variables."))

        axes_variables       <- axes_vars
        flag_merge_axes_vars <- TRUE
    }

    if (is.null(axes_vars)){
        print_message("ERROR", "<Axes variables> must be provided in quotation marks. Generating graphic will be aborted.")
        return(invisible(NULL))
    }

    if (flag_merge_axes_vars){
        axes_vars <- data_frame |> part_of_df(axes_vars)

        if (length(axes_vars) <= 1){
            if (length(axes_vars) == 0 || axes_vars == ""){
                # Create empty pseudo variable to let the rest of the program run as normal
                data_frame[[".temp_axes"]] <- 1
                axes_variables <- ".temp_axes"
                axes_vars      <- ".temp_axes"
                var_labels     <- c(var_labels, ".temp_axes" = "")
                formats[[".temp_axes"]] <- suppressMessages(discrete_format(" " = 1))
            }
        }
    }
    else{
        axes_vars <- data_frame |> part_of_df(axes_vars, check_only = TRUE)

        if (is.list(axes_vars)){
            print_message("ERROR", c("The provided <axes variables> '[axes_vars]' is not part of",
                                     "the data frame. Generating graphic will be aborted."), axes_vars = axes_vars[[1]])
            return(invisible(NULL))
        }
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Segment variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    segments <- get_origin_as_char(segments, substitute(segments))

    # Make sure that the variables provided are part of the data frame.
    if (length(segments) == 1 && segments == ""){
        segment_vars <- c()
    }
    else{
        segment_vars <- data_frame |> part_of_df(segments)
    }

    # Make sure there is no segment variable that is also an axes variable.
    segment_vars <- resolve_intersection(segment_vars, axes_vars, check_only = TRUE)

    if (is.list(segment_vars)){
        print_message("ERROR", c("The provided <segments> variable[?s] '[vars]' [?is/are] also part of",
                                 "the <axes_variables>. Generating graphic will be aborted."), vars = segment_vars[[1]])
        return(invisible(NULL))
    }

    # If no grouping variables are provided create a pseudo grouping variable
    if (length(segment_vars) == 0){
        segment_vars <- "pseudo_segment"
        data_frame[["pseudo_segment"]] <- 1

        # If only default percents are passed as statistics, change to sum or
        # otherwise one only gets 100 % in all categories.
        if (length(statistics) == 1 && statistics == "pct_group"){
            statistics <- "sum"
        }
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # By variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Convert to character vectors
    by <- get_origin_as_char(by, substitute(by))

    # Make sure that the variables provided are part of the data frame.
    by <- data_frame |> part_of_df(by)

    # Make sure there is no row/column variable that is also a by variable.
    variables <- c(axes_vars, segment_vars)
    by        <- resolve_intersection(by, variables, check_only = TRUE)

    if (is.list(by)){
        print_message("WARNING", c("The provided <by> variable '[by]' is also part of the <axes variables>",
                                   "or <segment> variables which is not allowed. <by> will be removed."),
                      by = by[[1]])
        by <- c()
    }

    if (length(by) == 1){
        if (by == ""){
            print_message("WARNING", "No valid <by> variables provided. <by> will be removed.")
            by <- c()
        }
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Weight
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    weight     <- get_origin_as_char(weight, substitute(weight))
    data_frame <- data_frame |> check_weight(weight)
    weight_var <- ".temp_weight"

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Values
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Convert to character vectors
    values <- get_origin_as_char(values, substitute(values))

    # If no value variables are provided generate a temporary variable which
    # outputs unweighted results.
    if (length(values) <= 1){
        if (length(values) == 0 || values == ""){
            values     <- ".temp_values"
            var_labels <- c(var_labels, .temp_values = "")
            data_frame[[values]] <- 1
        }
    }

    # Make sure there is no row/column variable that is also a value variable.
    values <- resolve_intersection(values, variables, check_only = TRUE)

    if (is.list(values)){
        print_message("ERROR", c("The provided <axes>/<segments> variable '[values]' is also part of",
                                 "the <values> variables. Generating graphic will be aborted."), values = values[[1]])
        return(invisible(NULL))
    }

    # Make sure that the variables provided are part of the data frame.
    values <- data_frame |> part_of_df(values)

    if (length(values) == 0){
        print_message("ERROR", "No valid <values> variables provided. Generating graphic will be aborted.")
        return(invisible(NULL))
    }

    values <- remove_doubled_values(values)

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Statistics
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    statistics <- get_origin_as_char(statistics, substitute(statistics))
    statistics <- tolower(statistics)

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Pre summarised data
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    pre_summed <- data_frame |> is_pre_summed(c(by, variables))

    # In case of using a pre summarised data frame, underscores are only allowed, if they carry
    # the statistics extension afterwards.
    if (pre_summed){
        # Only keep provided variables, otherwise it can happen later on that e.g. too many
        # variables are pivoted
        data_frame <- data_frame |> keep(by, variables, values, ".temp_weight")

        # If the TYPE variable isn't present in the data frame it will be generated here from
        # the provided variables.
        if (!"TYPE" %in% names(data_frame)){
            # For each observation check the non NA variables and combine their names in the TYPE
            # variable.
            data_frame[["TYPE"]] <- apply(data_frame[c(by, variables)], 1,
                function(variable){
                    var_name <- names(variable)[!is.na(variable)]

                    if (length(var_name) == 0){
                        NA_character_
                    }
                    else{
                        paste(var_name, collapse = "+")
                    }
                })

            data_frame |> data.table::setcolorder(c(by, variables, "TYPE"))
        }

        # Check if value variables have statistics extension
        extensions <- c("_sum", "_pct_group", "_pct_total", "_pct_value", "_pct", "_freq_g0",
                        "_freq", "_mean", "_median", "_mode", "_min", "_max", "_first",
                        "_last", "_sum_wgt", "_p[0-9]+$", "_sd", "_variance", "_missing")
        pattern    <- paste0("(", paste(extensions, collapse = "|"), ")$")

        # If one of the value variables hasn't got any of the above extension, add extensions automatically as provided
        if (!all(grepl(pattern, values))){
            print_message("WARNING", c("All <values> variables need to have the <statistic> extension in their variable name.",
                                       "You can use the function 'add_extension' to achieve this. Provided <statistic> will be used.",
                                       "This can lead to a wrong table structure, better add extensions by yourself."))

            data_frame <- data_frame |> add_extension(length(c(by, variables, "TYPE")) + 1,
                                                      rep(statistics, length(values))[1:length(values)])
        }

        # Set up options to make sure nothing errors below. Statistics is set to "mean"
        # because then summarise_plus takes a route where factor variables are kept in order.
        # With "sum" the order would be messed up.
        statistics <- "mean"
        pct_value  <- ""
        weight     <- NULL
        formats    <- list()

        rm(extensions, pattern)
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Statistics
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # If pct_value parameter is passed but is not selected as statistic, add it
    if (length(pct_value) > 0 && !"pct_value" %in% tolower(statistics)){
        if (!(length(pct_value) == 1 && pct_value == "")){
            statistics <- c(statistics, "pct_value")
        }
    }
    else if(length(pct_value) == 0 && "pct_value" %in% tolower(statistics)){
        print_message("NOTE", c("'pct_value' is specified in the statistics but the <pct_value> parameter",
                                " isn't set. 'pct_value' will be removed from statistics."))

        statistics <- statistics[!statistics %in% "pct_value"]
    }

    if (!pre_summed){
        list_of_statistics <- get_complete_statistics_list(statistics)

        # Check for invalid statistics
        valid_stats   <- statistics[statistics %in% c(names(list_of_statistics), "sum_wgt", "pct_value",
                                                      "pct_group", "pct_total", paste0("p", 1:100))]
        invalid_stats <- statistics[!statistics %in% c(names(list_of_statistics), "sum_wgt", "pct_value",
                                                       "pct_group", "pct_total", paste0("p", 1:100))]

        if (length(invalid_stats) > 0){
            print_message("WARNING", "<Statistic> '[invalid]' [?is/are] invalid and will be omitted.", invalid = invalid_stats)

            if (length(valid_stats) == 0){
                print_message("WARNING", "No valid <statistic> selected. 'sum' will be used.")

                statistics <- "sum"
            }
        }

        # This basically serves as the default parameter
        if (length(statistics) == 0){
            statistics <- "pct_group"
        }

        rm(list_of_statistics, invalid_stats)
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Percentages
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # If pct_value is selected, make sure sum is also part of statistics
    flag_remove_sum <- FALSE

    if (!"sum" %in% statistics){
        if ("pct_value" %in% tolower(statistics)){
            statistics      <- c(statistics, "sum")
            flag_remove_sum <- TRUE
        }
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Diagram
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Evaluate the diagram parameter to see if it is a function
    diagram_name <- get_origin_as_char(diagram, substitute(diagram))

    if (!is.function(diagram)){
        if (is.null(diagram_name)){
            diagram_name <- "Missing"
        }

        print_message("WARNING", "'[diagram_name]' is not a function. Vertical bars will be used instead.",
                      diagram_name = diagram_name)

        diagram <- match.fun("dg_vbars")
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Resolve macros
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    titles      <- apply_macro(titles)
    footnotes   <- apply_macro(footnotes)
    var_labels  <- apply_macro(var_labels)
    stat_labels <- apply_macro(stat_labels)

    ###########################################################################
    # Any Generating graphic starts
    ###########################################################################

    #-------------------------------------------------------------------------#
    monitor_df <- monitor_df |> monitor_next("Summary", "Summary")
    #-------------------------------------------------------------------------#
    print_step("MAJOR", "Computing stats")

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Some preparations beforehand
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Put together vector of grouping variables
    group_vars <- c(by, variables)

    # Put combinations in a single vector
    if (flag_merge_axes_vars){
        # On single axes variables combine them separately with the segments
        segment_part <- sprintf("(%s)", paste(segment_vars, collapse = ", "))
        combinations <- paste(axes_variables, segment_part, sep = " + ")
    }
    else{
        # On nested axes variables combine them together with the segments
        combinations <- c(axes_variables, sprintf("(%s)", paste(segment_vars, collapse = ", ")))
        combinations <- paste(combinations, collapse = " + ")
    }

    # In case by variables are specified, add by to group variables and build
    # additional combinations
    if (length(by) > 0){
        combinations <- as.vector(outer(by, combinations, paste, sep = "+"))
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Summarise data according to provided variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Compute statistics
    if (!pre_summed){
        # NOTE: By setting print_miss to always be TRUE there shouldn't be any arbitrary
        #       number of segments per group.
        graphic_tab <- suppressMessages(data_frame |>
              summarise_plus(class      = group_vars,
                             values     = values,
                             statistics = statistics,
                             formats    = formats,
                             weight     = weight_var,
                             nesting    = "all",
                             types      = combinations,
                             notes      = FALSE,
                             na.rm      = na.rm,
                             print_miss = TRUE)) |>
            collapse::fsubset(TYPE != "total") |>
            fuse_variables("segments", segment_vars)

        # On single axes variables fuse them into one variable
        if (flag_merge_axes_vars){
            graphic_tab <- suppressMessages(graphic_tab |>
                fuse_variables("axes", axes_vars) |>
                retain_variables("segments"))

            # Adjust variable vectors
            variables  <- variables[!variables   %in% axes_vars]
            group_vars <- group_vars[!group_vars %in% axes_vars]
            axes_vars  <- "axes"
            variables  <- c(variables, "axes")
            group_vars <- c(group_vars, "axes")
        }

        # Convert missing values to 0
        value_vars <- graphic_tab |> inverse(c(group_vars, "TYPE", "TYPE_NR", "DEPTH", "segments"))

        graphic_tab[value_vars] <- lapply(graphic_tab[value_vars], function(variable){
            variable[is.na(variable)] <- 0
            variable
        })
    }
    else{
        # With pre summarised data just take the input data frame
        graphic_tab <- data_frame
    }

    if (is.null(graphic_tab)){
        print_message("ERROR", "Table could not be computed. Execution will be aborted.")
        return(invisible(NULL))
    }

    # Convert grouping variables to factor to retain value order after sorting later on
    graphic_tab <- graphic_tab |> convert_factor(group_vars)

    # In case of pre summarised data frame remove the temporary weight variable
    if (pre_summed){
        graphic_tab <- graphic_tab |> collapse::fselect(-.temp_weight)
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Handle by variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # In case of by variables fuse them into one
    if (length(by) > 0){
        graphic_tab <- graphic_tab |> fuse_variables("by_vars", by)

        # Normally extract the first variable from the TYPE combination into a
        # separate BY variable.
        if (!pre_summed){
            graphic_tab[["BY"]]   <- sub("\\+.*", "", graphic_tab[["TYPE"]])
            graphic_tab[["TYPE"]] <- sub("^[^+]*\\+\\s*", "", graphic_tab[["TYPE"]])
        }
        # In case of pre summarised data frame it is not clear, at which position
        # the by variable is in the TYPE.
        else{
            # Get TYPE variable as list of variable combinations
            type_split <- strsplit(graphic_tab[["TYPE"]], "\\+")

            # If by variable was found in a variable combination, put it into
            # a separate variable.
            graphic_tab[["BY"]] <- vapply(type_split, function(obs){
                by_found <- obs[obs %in% by]

                if (length(by_found) > 0){
                    by_found[1]
                }
                else{
                    ""
                }
            }, character(1L))

            # The TYPE variable itself is put back together as all variables which
            # are no by-Variables.
            graphic_tab[["TYPE"]] <- vapply(type_split, function(obs){
                paste(obs[!obs %in% by], collapse = "+")
            }, character(1L))
        }

        # Convert to factor to keep them in order when sorting later
        graphic_tab <- graphic_tab |> convert_factor(c("BY", "by_vars"))
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Handle percentages based on value variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # In case percentages based on value variables should be computed
    if ("pct_value" %in% tolower(statistics) && length(pct_value) > 0){
        for (i in seq_along(pct_value)){
            value <- pct_value[[i]]
            name  <- names(pct_value)[i]

            # Separate provided variables first
            eval_vars <- trimws(strsplit(value, split = "/")[[1]])

            # Compute percentages
            if (paste0(eval_vars[1], "_sum") %in% names(graphic_tab) &&
                paste0(eval_vars[2], "_sum") %in% names(graphic_tab)){
                graphic_tab[[paste0(name, "_pct_value")]] <-
                    graphic_tab[[paste0(eval_vars[1], "_sum")]] * 100 /
                    graphic_tab[[paste0(eval_vars[2], "_sum")]]
            }
            # Without sum percentages can't be computed
            else{
                flag_remove_sum <- FALSE

                # Additional warnings for missing variables
                if (!eval_vars[1] %in% names(data_frame)){
                    print_message("WARNING", "Variable '[eval_vars]' not found in the data frame.", eval_vars = eval_vars[1])
                }
                if (!eval_vars[2] %in% names(data_frame)){
                    print_message("WARNING", "Variable '[eval_vars]' not found in the data frame.", eval_vars = eval_vars[2])
                }
            }
        }

        if (flag_remove_sum){
            graphic_tab <- graphic_tab |> dropp(":_sum")
        }

        rm(eval_vars, i, value, flag_remove_sum)
    }

    rm(data_frame)

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Round values
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # TODO: Revisit the ordering some time.

    # Reorder variables according to statistics. This is necessary because some
    # percentages can only be computed after summarise_plus and therefor aren't ordered.
    #if ("pct_group" %in% statistics){
    #    graphic_tab <- graphic_tab |> setcolorder_by_pattern(order_pct)
    #}

    graphic_tab <- graphic_tab |> setcolorder_by_pattern(statistics)

    # Get value variable names
    if (length(by) == 0){
        var_vector <- c(variables, "TYPE", "TYPE_NR", "DEPTH", "segments")
        value_vars <- graphic_tab |> inverse(var_vector)
    }
    else{
        var_vector <- c(variables, "TYPE", "TYPE_NR", "DEPTH", "by_vars", "BY", "segments")
        value_vars <- graphic_tab |> inverse(var_vector)
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Sort axes variables if there are expanded combinations. What this does is
    # putting the combinations together in a way, so that what belongs together is
    # printed together. Meaning same combination roots are put below each other.
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    # Sorting order: original not expanded base group, all axes variables
    # This order keeps the root combinations together but the last variables
    # apart from another.
    graphic_tab[["TYPE_ORIG"]] <- sub("\\s*\\+\\s*[^+]*$", "", graphic_tab[["TYPE"]])

    if (length(by) > 0){
        sort_vars <- c("TYPE_ORIG", "BY", "by_vars", axes_vars, "segments")
    }
    else{
        sort_vars <- c("TYPE_ORIG", axes_vars, "segments")
    }

    # Get the unique values per variable in order of appearance. This is crucial
    # to keep the base order as is.
    levels_list <- lapply(graphic_tab[sort_vars], function(variable){
        collapse::funique(unlist(variable))
    })

    # Convert row header variables to factors
    for (variable in sort_vars){
        var_levels <- levels_list[[variable]]

        graphic_tab[[variable]] <- factor(graphic_tab[[variable]],
                                          levels  = var_levels,
                                          ordered = TRUE,
                                          exclude = NULL)
    }

    # Actual sorting
    data.table::setorderv(graphic_tab, sort_vars)
    graphic_tab <- graphic_tab |> data.table::setcolorder(axes_vars, before = 1)

    # Save the TYPE variable to later determine which axes expressions belong to
    # which groups. But only do this if there really are multiple variables involved.
    if (length(axes_variables) > 1){
        graphic_tab[["axes_type"]] <- graphic_tab[["TYPE"]]
        graphic_tab <- graphic_tab |> data.table::setcolorder("axes_type", before = 1)
    }

    if (length(by) > 0){
        graphic_tab <- graphic_tab |> data.table::setcolorder("by_vars", before = 1)
    }

    # Convert back to character and drop TYPE variables
    graphic_tab[sort_vars] <- lapply(graphic_tab[sort_vars], as.character)
    graphic_tab <- graphic_tab |>
        drop_type_vars() |>
        collapse::fselect(-TYPE_ORIG)

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Prepare table format for output
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    #-------------------------------------------------------------------------#
    monitor_df <- monitor_df |> monitor_next("Excel prepare", "Format")
    #-------------------------------------------------------------------------#
    print_step("MAJOR", "Formatting tables")

    monitor_df <- monitor_df |> monitor_end()

    # In case no by variables are provided
    if (length(by) == 0){
        graphic_list <- generate_graphic(graphic_tab, axes_vars, "segments", statistics,
                                         by, titles, footnotes, var_labels, stat_labels,
                                         diagram, visuals, axes, dimensions,
                                         fine_tuning, add_texts, output, print, monitor_df = monitor_df)

        plot_element <- graphic_list[[1]]
        monitor_df   <- graphic_list[[2]]
    }
    # In case there are  by variables are provided
    else{
        graphic_list <- generate_graphic_by(graphic_tab, axes_vars, "segments", statistics,
                                            by, titles, footnotes, var_labels, stat_labels,
                                            diagram, visuals, axes, dimensions,
                                            fine_tuning, add_texts, output, na.rm, print, monitor_df)

        plot_element <- graphic_list[[1]]
        monitor_df   <- graphic_list[[2]]
    }

    print_closing(5)

    #-------------------------------------------------------------------------#
    monitor_df <- monitor_df |> monitor_end()
    monitor_df |> monitor_plot(draw_plot = monitor)
    #-------------------------------------------------------------------------#

    invisible(structure(list("table"   = graphic_tab,
                             "graphic" = plot_element,
                             "meta"    = graphic_list[[3]]), class = "qol_graphic"))
}


###############################################################################
# Format any table for excel output
###############################################################################
#' Format Any Table Output (Excel Based)
#'
#' @description
#' Format any table with the provided row and column variables. Statistics
#' can be anything available.
#'
#' @param graphic_tab The data frame which contains the information for this graphic.
#' @param axes_vars A vector containing the axes variables.
#' @param segment_vars A vector containing the segment variables.
#' @param statistics The user requested statistics.
#' @param by Separate the graphics output by the expressions of the provided variables.
#' @param titles Specify one or more table titles.
#' @param footnotes Specify one or more table footnotes.
#' @param var_labels A list in which is specified which label should be printed for
#' which variable instead of the variable name.
#' @param stat_labels A list in which is specified which label should be printed for
#' which statistic instead of the statistic name.
#' @param diagram Function that provides the generation of the main diagram area.
#' @param visuals Visual parameters set with [graphic_visuals()].
#' @param axes Axes parameters set with [graphic_axes()].
#' @param dimensions Dimension parameters set with [graphic_dimensions()].
#' @param fine_tuning Fine tuning parameters set with [graphic_fine_tuning()].
#' @param add_texts Use the [add_textbox()] function to freely place one or multiple textboxes.
#' @param output Output parameters set with [graphic_output()].
#' @param print TRUE by default. If TRUE prints the output, if FALSE doesn't print anything.
#' Can be used if one only wants to catch the output data frame and workbook with meta information.
#' @param by_info Text which contains the information which variable with which
#' expression is computed at the moment. Used for computation with by variables.
#' @param index Index of the current variable expression. Used for computation with
#' by variables.
#' @param monitor FALSE by default. If TRUE, outputs two charts to visualize the functions time consumption.
#'
#' @return
#' Returns a list containing a formatted Excel workbook as well as the monitoring
#' data frame.
#'
#' @noRd
generate_graphic <- function(graphic_tab,
                             axes_vars,
                             segment_vars,
                             statistics,
                             by,
                             titles,
                             footnotes,
                             var_labels,
                             stat_labels,
                             diagram,
                             visuals,
                             axes,
                             dimensions,
                             fine_tuning,
                             add_texts,
                             output,
                             print,
                             by_info        = NULL,
                             index          = NULL,
                             grid_positions = NULL,
                             monitor_df){
    #-------------------------------------------------------------------------#
    monitor_df <- monitor_df |> monitor_start("General design", "Format")
    #-------------------------------------------------------------------------#
    if (is.null(by_info)){ print_step("MINOR", "Set up viewport") }

    values <- utils::tail(names(graphic_tab), 1)
    # TODO: HANDLE MULTIPLE VALUE VARIABLES

    # Register font
    register_windows_font(visuals[["font"]])

    # Don't display values in interactive graphics. Also only single files can
    # be exported.
    if (output[["interactive"]]){
        visuals[["display_values"]] <- FALSE
    }

    # Setup main canvas
    grid_row    <- NULL
    grid_column <- NULL

    if (!is.null(grid_positions)){
        grid_row    <- grid_positions[["row"]]
        grid_column <- grid_positions[["column"]]
    }

    viewport <- setup_main_canvas(dimensions    = dimensions,
                                  layout_row    = grid_row,
                                  layout_column = grid_column)

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Setup titles and footnotes
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    if (is.null(by_info)){ print_step("MINOR", "Setup titles and footnotes") }

    # Draw the graphics background
    graphic_background <- grid::rectGrob(gp  = grid::gpar(fill = visuals[["graphic_background_color"]],
                                                          col  = visuals[["graphic_border_color"]],
                                                          lwd  = dimensions[["graphic_outline_thickness"]]),
                                         name = "graphic_background")

    # If titles and footnotes are given as a vector instead of single character,
    # merge the single parts together first.
    titles    <- paste(titles,    collapse = "\n")
    footnotes <- paste(footnotes, collapse = "\n")

    # Get titles and footnotes as graphical objects
    title_grob    <- add_title(titles, dimensions, visuals)
    footnote_grob <- add_footnote(footnotes, dimensions, visuals)
    origin_grob   <- add_graphic_origin(dimensions, visuals)

    # TODO: ADD ADDITIONAL SUB HEADLINE
    # Get graphic element heights
    title_height    <- abs(grid::convertHeight(grid::grobHeight(title_grob),    "cm", valueOnly = TRUE))
    footnote_height <- abs(grid::convertHeight(grid::grobHeight(footnote_grob), "cm", valueOnly = TRUE))
    origin_height   <- abs(grid::convertHeight(grid::grobHeight(origin_grob),   "cm", valueOnly = TRUE))

    # Get automatically set dimensions
    flag_auto_width  <- dimensions[["diagram_width"]]
    flag_auto_height <- dimensions[["diagram_height"]]

    dimensions[["diagram_start_left"]] <- ifelse(dimensions[["diagram_start_left"]] == "auto", dimensions[["margins"]], dimensions[["diagram_start_left"]])
    dimensions[["diagram_start_top"]]  <- get_diagram_start_cm(dimensions, title_height)
    dimensions[["diagram_width"]]      <- get_diagram_width_cm(dimensions)
    dimensions[["diagram_height"]]     <- get_diagram_height_cm(dimensions, title_height, footnote_height, origin_height)

    # Put the passed arguments into a list to pass them on to a function which
    # measures the majority of the dimensions and positions.
    arguments <- list(graphic_tab     = graphic_tab,
                      axes_vars       = c(axes_vars),
                      segment_vars    = c(segment_vars),
                      values          = c(values),
                      statistics      = c(statistics),
                      var_labels      = c(var_labels),
                      stat_labels     = c(stat_labels),
                      visuals         = visuals,
                      axes            = axes,
                      dimensions      = dimensions,
                      fine_tuning     = fine_tuning,
                      output          = output,
                      title_height    = title_height,
                      footnote_height = footnote_height,
                      origin_height   = origin_height)

    diagram_info <- get_diagram_dimensions(arguments)

    # Add a legend for the individual segments if specified
    segment_labels <- setup_legend(diagram_info, visuals, dimensions)

    # Adjust diagram dimensions according to legend presets, if legend is present
    if (length(segment_labels) > 1){
        arguments[["dimensions"]][["diagram_start_left"]] <- segment_labels[[2]]
        arguments[["dimensions"]][["diagram_start_top"]]  <- segment_labels[[3]]
        arguments[["dimensions"]][["diagram_width"]]      <- segment_labels[[4]]
        arguments[["dimensions"]][["diagram_height"]]     <- segment_labels[[5]]
        segment_labels <- grid::gList(segment_labels[[1]])
    }

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Build main diagram
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    if (is.null(by_info)){ print_step("MINOR", "Build main diagram") }

    # Draw main diagram
    main_grob <- diagram(arguments, diagram_info)

    # Go back to the main canvas to be able to draw additional textboxes freely
    back_to_the_root()

    # Reconstruct viewport so that the diagram children are drawn the righr way
    viewport_path <- c(grid::current.vpPath()[["name"]],
                       main_grob[["meta"]][["outer_viewport"]][["name"]],
                       main_grob[["meta"]][["inner_viewport"]][["name"]])

    viewport_tree <- grid::current.viewport() |>
        grid::vpStack(
            main_grob[["meta"]][["outer_viewport"]],
            main_grob[["meta"]][["inner_viewport"]])

    # Check if the add_textbox function was directly passed to the parameter.
    # In this case enclose it in a list.
    if (inherits(add_texts, "text") && inherits(add_texts, "grob")){
        add_texts <- list(add_texts)
    }

    # Make sure custom textboxes have a unique name or otherwise only the first
    # will be drawn multiple times.
    custom_textboxes <- lapply(seq_along(add_texts), function(textbox){
            grid::editGrob(add_texts[[textbox]],
                           vp   = grid::vpPath("main_canvas"),
                           name = paste0("custom_textbox", textbox))
        })

    if (length(custom_textboxes) == 0){
        custom_textboxes <- list(grid::nullGrob(name = "no_textboxes"))
    }

    # Put together the whole graphic
    whole_graphic <- grid::gTree(children = do.call(
        grid::gList, c(list(grid::editGrob(graphic_background,     vp = grid::vpPath("main_canvas")),
                            grid::editGrob(title_grob,             vp = grid::vpPath("main_canvas")),
                            grid::editGrob(main_grob[["graphic"]], vp = grid::vpPath(viewport_path)),
                            grid::editGrob(footnote_grob,          vp = grid::vpPath("main_canvas")),
                            grid::editGrob(origin_grob,            vp = grid::vpPath("main_canvas"))),
                            segment_labels,
                            custom_textboxes)),
        childrenvp = viewport_tree,
        name       = "graphic" )

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Output graphic
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    if (is.null(by_info)){ print_step("MAJOR", "Output graphic") }

    # Draw and save the graphic
    # NOTE: To leave it like this in a situation with by-variables, leads to multiple
    #       draw calls, meaning one draw call per iteration. This should probably be
    #       reworked to just one draw call at the end of the by loop of the function
    #       below. But at the moment I can't get the graphics to draw in a grid with
    #       a single draw call. I think the master_layout somehow interferes with
    #       the viewport construction in this function. Revisit some time.
    svg_string <- output_graphic(whole_graphic, visuals, dimensions, fine_tuning, output, main_grob[["meta"]], print, by_info)

    grid::popViewport()

    #-------------------------------------------------------------------------#
    monitor_df <- monitor_df |> monitor_start("Special design", "Format")
    #-------------------------------------------------------------------------#

    monitor_df <- monitor_df |> monitor_end()

    # Return graphic information
    list(whole_graphic, monitor_df, main_grob[["meta"]], svg_string)
}


###############################################################################
# Format grouped by tables for excel output
###############################################################################
#' Format Any Table Output with by Variables (Excel Based)
#'
#' @description
#' Format any table with the provided row and column variables. Data frame is split
#' by by-variables, each table gets printed on a different sheet.
#'
#' @param graphic_tab The data frame which contains the information for this graphic.
#' @param axes_vars A vector containing the axes variables.
#' @param segment_vars A vector containing the segment variables.
#' @param statistics The user requested statistics.
#' @param by Separate the graphics output by the expressions of the provided variables.
#' @param titles Specify one or more table titles.
#' @param footnotes Specify one or more table footnotes.
#' @param var_labels A list in which is specified which label should be printed for
#' which variable instead of the variable name.
#' @param stat_labels A list in which is specified which label should be printed for
#' which statistic instead of the statistic name.
#' @param diagram Function that provides the generation of the main diagram area.
#' @param visuals Visual parameters set with [graphic_visuals()].
#' @param axes Axes parameters set with [graphic_axes()].
#' @param dimensions Dimension parameters set with [graphic_dimensions()].
#' @param fine_tuning Fine tuning parameters set with [graphic_fine_tuning()].
#' @param add_texts Use the [add_textbox()] function to freely place one or multiple textboxes.
#' @param output Output parameters set with [graphic_output()].
#' @param na.rm If TRUE removes all NA values from the tabulation.
#' @param print TRUE by default. If TRUE prints the output, if FALSE doesn't print anything.
#' Can be used if one only wants to catch the output data frame and workbook with meta information.
#' @param monitor FALSE by default. If TRUE, outputs two charts to visualize the functions time consumption.
#'
#' @return
#' Returns a list containing a formatted Excel workbook as well as the monitoring
#' data frame.
#'
#' @noRd
generate_graphic_by <- function(graphic_tab,
                                axes_vars,
                                segment_vars,
                                statistics,
                                by,
                                titles,
                                footnotes,
                                var_labels,
                                stat_labels,
                                diagram,
                                visuals,
                                axes,
                                dimensions,
                                fine_tuning,
                                add_texts,
                                output,
                                na.rm,
                                print,
                                monitor_df){
    grid::grid.newpage()

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Calculate grid dimensions
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    #---------------------------------------------------------------------#
    monitor_df <- monitor_df |> monitor_start("Calculate grid", "Calculate grid")
    #---------------------------------------------------------------------#

    number_of_values <- 0

    # Loop through all by variable and add up the total number of values
    for (by_var in by){
        graphic_temp <- graphic_tab |> collapse::fsubset(graphic_tab[["BY"]] == by_var)

        current_values <- collapse::funique(graphic_temp[["by_vars"]])

        number_of_values <- number_of_values + length(current_values)
    }

    # On automatic calculation: calculate the grid dimensions to be equaly
    # distributed among rows and columns.
    number_of_columns <- output[["grid_columns"]]

    if (is.character(number_of_columns)){
        number_of_columns <- ceiling(sqrt(number_of_values))
    }

    number_of_rows <- ceiling(number_of_values / number_of_columns)

    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # Loop through all by variables
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    index        <- 1
    cell_counter <- 1
    graphic_list <- list()

    for (by_var in by){
        #---------------------------------------------------------------------#
        monitor_df <- monitor_df |> monitor_start(paste0("Graphic prepare (", by_var, ")"), "Format by")
        #---------------------------------------------------------------------#

        # Select by variables one by one
        graphic_by <- graphic_tab |> collapse::fsubset(graphic_tab[["BY"]] == by_var)

        # Extract unique values
        if (anyNA(graphic_by[["by_vars"]])){
            values <- c(collapse::funique(collapse::na_omit(graphic_by[["by_vars"]])), NA)
        }
        else{
            values <- collapse::funique(graphic_by[["by_vars"]])
        }

        #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        # Set up master viewport to be able to arrange single graphics in grid
        # layout.
        #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        # Set up whole grid graphic dimensions in cm
        grid_width  <- dimensions[["graphic_width"]]  * number_of_columns
        grid_height <- dimensions[["graphic_height"]] * number_of_rows

        # Define the master viewport with a grid layout
        master_layout <- grid::viewport(width  = grid::unit(grid_width,  "cm"),
                                        height = grid::unit(grid_height, "cm"),
                                        name   = "master_grid",
                                        layout = grid::grid.layout(nrow = number_of_rows,
                                                                   ncol = number_of_columns))

        grid::pushViewport(master_layout)

        # Initialize a list which captures all single graphic objects
        graphic_list <- list()
        svg_list     <- list()
        meta_list    <- list()

        #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        # Loop through all unique values to generate tables per expression
        #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        monitor_df <- monitor_df |> monitor_end()

        for (value in values){
            # In case NAs are removed
            if (is.na(value) && na.rm){
                next
            }

            #-----------------------------------------------------------------#
            monitor_df <- monitor_df |> monitor_start(paste0("Excel (", by_var, "_", value, ")"), "Format by")
            #-----------------------------------------------------------------#
            print_step("MINOR", "[by] = [value]", by = by_var, value = value)

            # Put additional by info together with the information which by variable
            # and which value is currently filtered.
            by_info <- paste0(by_var, " = ", value)

            # Filter table by current by variable and value
            if (!is.na(value)){
                graphic_temp <- graphic_by |>
                    collapse::fsubset(graphic_by[["by_vars"]] == value)
            }
            else{
                graphic_temp <- graphic_by |>
                    collapse::fsubset(is.na(graphic_by[["by_vars"]]))
            }

            graphic_temp <- graphic_temp |> dropp("BY", "by_vars")

            # Replace by info in the titles
            if (length(titles) > 0){
                titles_temp <- gsub("\\[by_var\\]", value, titles)
            }
            # Or use by info as title, if there are no titles
            else{
                titles_temp <- by_info
            }

            # Replace by info in the footnotes
            if (length(footnotes) > 0){
                footnotes_temp <- gsub("\\[by_var\\]", value, footnotes)
            }
            # Otherwise just leave footnotes empty
            else{
                footnotes_temp <- footnotes
            }

            # Calculate the actual position in the grid
            grid_row    <- ceiling(cell_counter / number_of_columns)
            grid_column <- cell_counter - ((grid_row - 1) * number_of_columns)

            grid_positions <- list(row = grid_row, column = grid_column)

            # Generate tables as normal but base is filtered data frame
            current_graphic <- generate_graphic(graphic_temp,
                                                axes_vars,
                                                segment_vars,
                                                statistics,
                                                by,
                                                titles_temp,
                                                footnotes_temp,
                                                var_labels,
                                                stat_labels,
                                                diagram,
                                                visuals,
                                                axes,
                                                dimensions,
                                                fine_tuning,
                                                add_texts,
                                                output,
                                                print,
                                                value, # by_info passed as value, so that value can be added to the file name on saving
                                                index,
                                                grid_positions,
                                                NULL)


            # Save the graphic object into a list
            if (!is.na(value)){
                graphic_list[[value]] <- current_graphic[[1]]
                svg_list[[value]]     <- current_graphic[[4]]
                meta_list[[value]]    <- current_graphic[[3]]
            }
            else{
                graphic_list[["Missing"]] <- current_graphic[[1]]
                svg_list[["Missing"]]     <- current_graphic[[4]]
                meta_list[["Missing"]]    <- current_graphic[[3]]
            }

            index        <- index + 1
            cell_counter <- cell_counter + 1

            monitor_df <- monitor_df |> monitor_end()
        }
    }

    grid::popViewport()

    # Export the whole grid as one graphic
    output_grid(list(graphic_width = grid_width, graphic_height = grid_height),
                fine_tuning, output, svg_list, graphic_tab, print)

    # Return graphic information
    list(graphic_list, monitor_df, meta_list)
}
